# docker-compose.yml

version: "3.8"

services:
  backend:
    container_name: afro-chat-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --lifespan=on --loop uvloop --http httptools --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: PostgresDB
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=AfroChat

volumes:
  postgres_data:
