"""Create Version Control Table

Revision ID: 0043f10bfd4a
Revises: 672a17644907
Create Date: 2024-01-24 15:10:12.850100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0043f10bfd4a"
down_revision = "672a17644907"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "version",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        op.f("ix_version_version_id"), "version", ["version_id"], unique=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_version_version_id"), table_name="version")
    op.drop_table("version")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
