"""persona functional tool access list

Revision ID: 009fd70d7117
Revises: b2477b25bdd9
Create Date: 2024-01-29 15:44:09.206100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "009fd70d7117"
down_revision = "b2477b25bdd9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "functional_tools",
            sa.ARRAY(sa.String(length=1000)),
            server_default=sa.text("'{}'::character varying[]"),
            nullable=False,
        ),
    )
    op.drop_column("persona", "has_functional_tool_access")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "has_functional_tool_access",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("persona", "functional_tools")
    # ### end Alembic commands ###
