"""Add preferable entity table

Revision ID: 301955484608
Revises: a6a6bd131ca9
Create Date: 2024-02-23 08:12:06.294196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "301955484608"
down_revision = "a6a6bd131ca9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
