"""remove group topic column

Revision ID: 3127afa6a05c
Revises: 97fe85b089de
Create Date: 2024-01-29 09:00:03.610848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3127afa6a05c"
down_revision = "97fe85b089de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_telegram_group_message_group_topic", table_name="telegram_group_message"
    )
    op.drop_column("telegram_group_message", "group_topic")

    op.add_column(
        "telegram_group_message",
        sa.Column(
            "group_topic",
            sa.BIGINT(),
            server_default="-1",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_telegram_group_message_group_topic"),
        "telegram_group_message",
        ["group_topic"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_group_message_group_topic"),
        table_name="telegram_group_message",
    )
    op.drop_column("telegram_group_message", "group_topic")

    op.add_column(
        "telegram_group_message",
        sa.Column(
            "group_topic",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=False,
            server_default="DEFAULT_GROUP",
        ),
    )
    op.create_index(
        "ix_telegram_group_message_group_topic",
        "telegram_group_message",
        ["group_topic"],
        unique=False,
    )
    # ### end Alembic commands ###
