"""added AskTelegram Table

Revision ID: 3df5e11b5cae
Revises: d83af8c2baea
Create Date: 2023-12-28 07:52:18.109303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3df5e11b5cae"
down_revision = "d83af8c2baea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_telegram",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(length=100000), nullable=False),
        sa.Column("answer", sa.String(length=100000), nullable=False),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id"),
    )
    op.create_index(op.f("ix_ask_telegram_id"), "ask_telegram", ["id"], unique=True)
    op.create_index(
        op.f("ix_ask_telegram_user_id"), "ask_telegram", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ask_telegram_user_id"), table_name="ask_telegram")
    op.drop_index(op.f("ix_ask_telegram_id"), table_name="ask_telegram")
    op.drop_table("ask_telegram")
    # ### end Alembic commands ###
