"""add rank column to personas

Revision ID: 5dafe26fa60b
Revises: 0043f10bfd4a
Create Date: 2024-01-25 07:13:07.314631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5dafe26fa60b"
down_revision = "0043f10bfd4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona", sa.Column("rank", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "rank")
    # ### end Alembic commands ###
