"""persona creator and visibility

Revision ID: 637ad796cb9a
Revises: 6b2c9512f499
Create Date: 2024-01-16 11:11:37.779431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "637ad796cb9a"
down_revision = "6b2c9512f499"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "visible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "visible")
    op.drop_column("persona", "updated_at")
    # ### end Alembic commands ###
