"""added group_id, groupd_name message_id tables

Revision ID: 672a17644907
Revises: cac332141255
Create Date: 2024-01-23 10:50:49.779573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "672a17644907"
down_revision = "cac332141255"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_generated_images",
        sa.Column(
            "group_id", sa.BIGINT(), server_default="-1001887387943", nullable=False
        ),
    )
    op.add_column(
        "user_generated_images",
        sa.Column(
            "group_name",
            sa.String(length=1000),
            server_default="AfroChat Discussion",
            nullable=False,
        ),
    )
    op.add_column(
        "user_generated_images",
        sa.Column(
            "message_id", sa.String(length=100), server_default="-99", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_user_generated_images_message_id"),
        "user_generated_images",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_generated_images_message_id"), table_name="user_generated_images"
    )
    op.drop_column("user_generated_images", "message_id")
    op.drop_column("user_generated_images", "group_name")
    op.drop_column("user_generated_images", "group_id")
    # ### end Alembic commands ###
