"""added is_archived and is_developer columns

Revision ID: 67499817c8d9
Revises: bcc0aa1df9cb
Create Date: 2024-01-03 08:26:15.891575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67499817c8d9"
down_revision = "bcc0aa1df9cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "sub_tool",
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_developer",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_developer")
    op.drop_column("sub_tool", "is_archived")
    op.drop_column("persona", "is_archived")
    # ### end Alembic commands ###
