"""Add a signup platform column to user

Revision ID: 6b2c9512f499
Revises: 67499817c8d9
Create Date: 2024-01-15 14:39:05.604641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b2c9512f499"
down_revision = "67499817c8d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("signup_platform", sa.Integer(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "signup_platform")
    # ### end Alembic commands ###
