"""persona external tool

Revision ID: 710d2afda199
Revises: 637ad796cb9a
Create Date: 2024-01-18 22:53:51.001372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "710d2afda199"
down_revision = "637ad796cb9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "has_functional_tool_access",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "has_functional_tool_access")
    # ### end Alembic commands ###
