"""added updated at for chat sessions

Revision ID: 9320e3a6a3f9
Revises: c2e2ae27d593
Create Date: 2023-12-28 15:30:13.295041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9320e3a6a3f9"
down_revision = "c2e2ae27d593"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_session",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_session", "updated_at")
    # ### end Alembic commands ###
