"""added full_name row

Revision ID: 97fe85b089de
Revises: b2477b25bdd9
Create Date: 2024-01-26 08:17:28.852015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97fe85b089de"
down_revision = "b2477b25bdd9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_telegram", sa.Column("full_name", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_telegram", "full_name")
    # ### end Alembic commands ###
