"""added created at column for the ask_telegram table

Revision ID: a6a6bd131ca9
Revises: c44fdbe1830c
Create Date: 2024-02-01 11:41:26.218035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6a6bd131ca9"
down_revision = "c44fdbe1830c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ask_telegram",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ask_telegram", "created_at")
    # ### end Alembic commands ###
