"""Added Group Messages Table

Revision ID: b2477b25bdd9
Revises: 5dafe26fa60b
Create Date: 2024-01-25 15:18:10.371313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2477b25bdd9"
down_revision = "5dafe26fa60b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_group_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_id", sa.BIGINT(), nullable=False),
        sa.Column("group_id", sa.BIGINT(), nullable=False),
        sa.Column("group_name", sa.String(length=1000), nullable=False),
        sa.Column("group_topic", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.BIGINT(), nullable=False),
        sa.Column("text", sa.String(length=100000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telegram_group_message_group_id"),
        "telegram_group_message",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_group_message_group_topic"),
        "telegram_group_message",
        ["group_topic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_group_message_id"),
        "telegram_group_message",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_telegram_group_message_telegram_id"),
        "telegram_group_message",
        ["telegram_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_group_message_telegram_id"),
        table_name="telegram_group_message",
    )
    op.drop_index(
        op.f("ix_telegram_group_message_id"), table_name="telegram_group_message"
    )
    op.drop_index(
        op.f("ix_telegram_group_message_group_topic"),
        table_name="telegram_group_message",
    )
    op.drop_index(
        op.f("ix_telegram_group_message_group_id"), table_name="telegram_group_message"
    )
    op.drop_table("telegram_group_message")
    # ### end Alembic commands ###
