"""generated image counter

Revision ID: bcc0aa1df9cb
Revises: 10a94fc24dad
Create Date: 2024-01-02 09:10:02.292492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bcc0aa1df9cb"
down_revision = "10a94fc24dad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_generated_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("prompt", sa.String(length=10000), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_generated_images_id"),
        "user_generated_images",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_generated_images_image_url"),
        "user_generated_images",
        ["image_url"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_generated_images_user_id"),
        "user_generated_images",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_generated_images_user_id"), table_name="user_generated_images"
    )
    op.drop_index(
        op.f("ix_user_generated_images_image_url"), table_name="user_generated_images"
    )
    op.drop_index(
        op.f("ix_user_generated_images_id"), table_name="user_generated_images"
    )
    op.drop_table("user_generated_images")
    # ### end Alembic commands ###
