"""added message from column for the Chat Messages

Revision ID: c2e2ae27d593
Revises: 3df5e11b5cae
Create Date: 2023-12-28 10:36:38.564270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2e2ae27d593"
down_revision = "3df5e11b5cae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message",
        sa.Column("message_from", sa.INTEGER(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message", "message_from")
    # ### end Alembic commands ###
