"""added new column group id on ask_telegram table

Revision ID: c44fdbe1830c
Revises: e77f9b535352
Create Date: 2024-02-01 11:34:41.556243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c44fdbe1830c"
down_revision = "e77f9b535352"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ask_telegram",
        sa.Column("group_id", sa.BIGINT(), server_default="99", nullable=False),
    )
    op.create_index(
        op.f("ix_ask_telegram_group_id"), "ask_telegram", ["group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ask_telegram_group_id"), table_name="ask_telegram")
    op.drop_column("ask_telegram", "group_id")
    # ### end Alembic commands ###
