"""added llm model to subtool, persona models

Revision ID: cac332141255
Revises: 89a43d58e384
Create Date: 2024-01-23 09:02:08.577981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cac332141255"
down_revision = "89a43d58e384"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message",
        sa.Column(
            "llm_model",
            sa.String(length=100),
            server_default="gpt-3.5-turbo",
            nullable=False,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "llm_model",
            sa.String(length=100),
            server_default="gpt-3.5-turbo",
            nullable=False,
        ),
    )
    op.add_column(
        "sub_tool",
        sa.Column(
            "llm_model",
            sa.String(length=100),
            server_default="gpt-3.5-turbo",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sub_tool", "llm_model")
    op.drop_column("persona", "llm_model")
    op.drop_column("chat_message", "llm_model")
    # ### end Alembic commands ###
