"""first commit

Revision ID: d83af8c2baea
Revises: 
Create Date: 2023-12-27 15:40:14.261717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d83af8c2baea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.String(length=50), nullable=False),
        sa.Column("firstname", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tool",
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("tool_desc", sa.String(length=5000), nullable=False),
        sa.Column("tool_image", sa.String(length=200), nullable=False),
        sa.Column("default_color", sa.String(length=10), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("tool_id"),
    )
    op.create_index(op.f("ix_tool_tool_id"), "tool", ["tool_id"], unique=True)
    op.create_index(op.f("ix_tool_tool_name"), "tool", ["tool_name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_activated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "persona",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("persona_image", sa.String(length=200), nullable=False),
        sa.Column("default_color", sa.String(length=10), nullable=False),
        sa.Column("initial_prompt", sa.String(length=10000), nullable=False),
        sa.Column("persona_type", sa.String(length=50), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.Column("long_description", sa.String(length=3000), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_uuid"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_creator_uuid"), "persona", ["creator_uuid"], unique=False
    )
    op.create_index(op.f("ix_persona_full_name"), "persona", ["full_name"], unique=True)
    op.create_index(op.f("ix_persona_id"), "persona", ["id"], unique=True)
    op.create_table(
        "sub_tool",
        sa.Column("sub_tool_id", sa.UUID(), nullable=False),
        sa.Column("sub_tool_name", sa.String(length=100), nullable=False),
        sa.Column("sub_tool_description", sa.String(length=5000), nullable=False),
        sa.Column("sub_tool_initial_prompt", sa.String(length=10000), nullable=False),
        sa.Column("sub_tool_image", sa.String(length=200), nullable=False),
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tool.tool_id"],
        ),
        sa.PrimaryKeyConstraint("sub_tool_id"),
    )
    op.create_index(
        op.f("ix_sub_tool_sub_tool_id"), "sub_tool", ["sub_tool_id"], unique=True
    )
    op.create_index(
        op.f("ix_sub_tool_sub_tool_name"), "sub_tool", ["sub_tool_name"], unique=True
    )
    op.create_table(
        "telegram_ask",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=100000), nullable=False),
        sa.Column("answer", sa.String(length=100000), nullable=False),
        sa.Column("token_usage", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telegram_conversation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("persona", sa.String(length=50), nullable=False),
        sa.Column("system_prompt", sa.String(length=100000), nullable=False),
        sa.Column("total_tokens", sa.INTEGER(), server_default="0", nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_email",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "is_activated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "email"),
    )
    op.create_index(op.f("ix_user_email_email"), "user_email", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_email_user_id"), "user_email", ["user_id"], unique=False
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_info_creator_id"), "user_info", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_info_first_name"), "user_info", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_user_info_id"), "user_info", ["id"], unique=True)
    op.create_index(
        op.f("ix_user_info_last_name"), "user_info", ["last_name"], unique=False
    )
    op.create_index(
        op.f("ix_user_info_user_id"), "user_info", ["user_id"], unique=False
    )
    op.create_table(
        "user_password",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_password_user_id"), "user_password", ["user_id"], unique=False
    )
    op.create_table(
        "user_phone_number",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "is_activated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "phone_number"),
    )
    op.create_index(
        op.f("ix_user_phone_number_phone_number"),
        "user_phone_number",
        ["phone_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_phone_number_user_id"),
        "user_phone_number",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_profile_picture",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("profile_picture", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_profile_picture_user_id"),
        "user_profile_picture",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_telegram",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("telegram_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "telegram_id"),
    )
    op.create_index(
        op.f("ix_user_telegram_telegram_id"),
        "user_telegram",
        ["telegram_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_telegram_user_id"), "user_telegram", ["user_id"], unique=False
    )
    op.create_table(
        "chat_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_message", sa.String(length=10000), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("share_able_link", sa.String(length=500), nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), server_default="0", nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=True),
        sa.Column("sub_tool_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_tool_id"],
            ["sub_tool.sub_tool_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_session_id"), "chat_session", ["id"], unique=True)
    op.create_table(
        "email_otp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("otp", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["email"],
            ["user_email.email"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_otp_email"), "email_otp", ["email"], unique=False)
    op.create_index(
        op.f("ix_email_otp_user_id"), "email_otp", ["user_id"], unique=False
    )
    op.create_table(
        "phone_otp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("otp", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["phone_number"],
            ["user_phone_number.phone_number"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phone_otp_phone_number"), "phone_otp", ["phone_number"], unique=False
    )
    op.create_index(
        op.f("ix_phone_otp_user_id"), "phone_otp", ["user_id"], unique=False
    )
    op.create_table(
        "preferable_persona",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "persona_id"),
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote", sa.String(length=10000), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_id"), "quotes", ["id"], unique=True)
    op.create_table(
        "telegram_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.String(length=100000), nullable=False),
        sa.Column("token_usage", sa.INTEGER(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["telegram_conversation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("message", sa.String(length=100000), nullable=False),
        sa.Column("token_usage", sa.INTEGER(), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_session_id"], ["chat_session.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_message_id"), "chat_message", ["id"], unique=True)
    op.create_table(
        "summarized_chat_session_snap_shot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=False),
        sa.Column("summarized_content", sa.String(length=10000), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("token_usage", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_session_id"], ["chat_session.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summarized_chat_session_snap_shot_id"),
        "summarized_chat_session_snap_shot",
        ["id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_summarized_chat_session_snap_shot_id"),
        table_name="summarized_chat_session_snap_shot",
    )
    op.drop_table("summarized_chat_session_snap_shot")
    op.drop_index(op.f("ix_chat_message_id"), table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_table("telegram_message")
    op.drop_index(op.f("ix_quotes_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_table("preferable_persona")
    op.drop_index(op.f("ix_phone_otp_user_id"), table_name="phone_otp")
    op.drop_index(op.f("ix_phone_otp_phone_number"), table_name="phone_otp")
    op.drop_table("phone_otp")
    op.drop_index(op.f("ix_email_otp_user_id"), table_name="email_otp")
    op.drop_index(op.f("ix_email_otp_email"), table_name="email_otp")
    op.drop_table("email_otp")
    op.drop_index(op.f("ix_chat_session_id"), table_name="chat_session")
    op.drop_table("chat_session")
    op.drop_index(op.f("ix_user_telegram_user_id"), table_name="user_telegram")
    op.drop_index(op.f("ix_user_telegram_telegram_id"), table_name="user_telegram")
    op.drop_table("user_telegram")
    op.drop_index(
        op.f("ix_user_profile_picture_user_id"), table_name="user_profile_picture"
    )
    op.drop_table("user_profile_picture")
    op.drop_index(op.f("ix_user_phone_number_user_id"), table_name="user_phone_number")
    op.drop_index(
        op.f("ix_user_phone_number_phone_number"), table_name="user_phone_number"
    )
    op.drop_table("user_phone_number")
    op.drop_index(op.f("ix_user_password_user_id"), table_name="user_password")
    op.drop_table("user_password")
    op.drop_index(op.f("ix_user_info_user_id"), table_name="user_info")
    op.drop_index(op.f("ix_user_info_last_name"), table_name="user_info")
    op.drop_index(op.f("ix_user_info_id"), table_name="user_info")
    op.drop_index(op.f("ix_user_info_first_name"), table_name="user_info")
    op.drop_index(op.f("ix_user_info_creator_id"), table_name="user_info")
    op.drop_table("user_info")
    op.drop_index(op.f("ix_user_email_user_id"), table_name="user_email")
    op.drop_index(op.f("ix_user_email_email"), table_name="user_email")
    op.drop_table("user_email")
    op.drop_table("telegram_conversation")
    op.drop_table("telegram_ask")
    op.drop_index(op.f("ix_sub_tool_sub_tool_name"), table_name="sub_tool")
    op.drop_index(op.f("ix_sub_tool_sub_tool_id"), table_name="sub_tool")
    op.drop_table("sub_tool")
    op.drop_index(op.f("ix_persona_id"), table_name="persona")
    op.drop_index(op.f("ix_persona_full_name"), table_name="persona")
    op.drop_index(op.f("ix_persona_creator_uuid"), table_name="persona")
    op.drop_table("persona")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tool_tool_name"), table_name="tool")
    op.drop_index(op.f("ix_tool_tool_id"), table_name="tool")
    op.drop_table("tool")
    op.drop_table("telegram_user")
    # ### end Alembic commands ###
