"""add is_premium to persona, tool and subtool

Revision ID: e77f9b535352
Revises: b43b65f46a76
Create Date: 2024-01-31 07:34:38.512268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e77f9b535352"
down_revision = "b43b65f46a76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "sub_tool",
        sa.Column(
            "is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "tool",
        sa.Column(
            "is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool", "is_premium")
    op.drop_column("sub_tool", "is_premium")
    op.drop_column("persona", "is_premium")
    # ### end Alembic commands ###
