"""Remove foreign key constraint from prerferablepersona

Revision ID: ecf1ef0c6edb
Revises: 301955484608
Create Date: 2024-02-23 08:16:18.936099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecf1ef0c6edb"
down_revision = "301955484608"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "preferable_persona_persona_id_fkey", "preferable_persona", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "preferable_persona_persona_id_fkey",
        "preferable_persona",
        "persona",
        ["persona_id"],
        ["id"],
    )
    # ### end Alembic commands ###
